### ISSUE TITLE
Problem installing vim-ide

### ISSUE THREAD

**Issue by daveshields** [farazdagi/vim-ide#3]
Saw your post on twitter, decided to take your code for a spin:
Problem 1) Post says repo is vim-go-ide. I just see vim-id in your repo list.
Problem 2) When I ran
# git submodule update
I got a message: Clone of Backrush/vimcode-git  failed. Could not read from remote repository.

thanks,dave

**Comment by farazdagi** [comment]
Dave,

Regarding 2: You do not need to run `git submodule update`, just clone (which will pull all the necessary plugins as copies in `bundle` folder of `~/.vim_go_runtime`) and run the install script.

Regarding 1: the repo **is** vim-go-ide, and it is located here: https://github.com/farazdagi/vim-go-ide

I will update this repository (which is outdated)
